### デート情報の取得
GET http://localhost:8000/meetings HTTP/1.1

### デート詳細の取得
GET http://localhost:8000/meetings/1 HTTP/1.1

### デート情報の更新（編集）
PUT http://localhost:8000/meetings/1 HTTP/1.1
Content-Type: application/json

{
  "title": "編集されたデート",
  "location": "渋谷",
  "date": "2025-03-08",
  "my_appearance_image_path": "",
  "meeting_photo": "date_photo10.jpg",
  "event_names": "美術館\nカフェ",
  "partner_appearances": "白ワンピース\nロングヘア",
  "talked_topics": "映画の話\n趣味の話",
  "partner_good_points": "笑顔が素敵\n丁寧な話し方",
  "todo_for_next": "次のデート場所を探す\nLINEを送る"
}

### デート情報の新規登録
POST http://localhost:8000/meetings HTTP/1.1
Content-Type: application/json

{
  "title": "新しいデート",
  "location": "新宿",
  "date": "2025-05-30",
  "event_names": "映画館\nカフェ",
  "partner_appearances": "黒髪\nスーツ",
  "talked_topics": "旅行の話\n仕事の話",
  "partner_good_points": "話し方が丁寧\n姿勢が良い",
  "todo_for_next": "次は美術館に行く\nお土産を買う",
  "meeting_photo": "",
  "my_appearance_image_path": "test.jpg"
}

### デート情報の削除（複数ID対応）
POST http://localhost:8000/meetings/delete HTTP/1.1
Content-Type: application/json

{
  "ids": [1, 2, 3]
}

### 良いところ一覧の取得
GET http://localhost:8000/goodpoints HTTP/1.1

### ユーザー登録(メール認証後)
POST http://localhost:8000/register
Content-Type: application/json

{
  "name": "横越秀",
  "phone": "09012345678",
  "email": "test@test.com",
  "password": "password123",
  "code":"970065"
}

### メール認証
POST http://localhost:8000/send_verification_code
Content-Type: application/json

{
  "email": "test@test.com"
}


### ログイン
POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### ログイン状態検証
GET http://localhost:8000/verify-user/1 HTTP/1.1

### ユーザー情報の取得
GET http://localhost:8000/users/4
Content-Type: application/json


### ユーザー情報の更新（ユーザー名とパスワード）
PUT http://localhost:8000/users/1
Content-Type: application/json

{
  "name": "新しい名前",
  "password": "newpassword123"
}

### 次の予定情報の取得
GET http://localhost:8000/next
Content-Type: application/json